### ISSUE TITLE
QA release v0.2

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy-glacier/s-k8-releases#39]
Please test OVA installation: 
https://glasswall-proxy-ova.s3.us-east-2.amazonaws.com/glasswall-proxy-cb131a57ba2aff33ec5938a283bf3747dbe91ee1.ova

Instructions: https://github.com/k8-proxy/s-k8-releases/blob/master/README.md

Deliverable: 
1.- let us know any update in the documented instructions
2.- Record a video of the reverse proxy correctly working for gov.uk

**Comment by Abby595** [comment]
@GINAGC the link is providing access denied even after EC2 access 
![aws](https://user-images.githubusercontent.com/71430578/94132118-1ff94700-fe5f-11ea-9595-78500f818443.PNG)
