### ISSUE TITLE
Release chrome extension project

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy-glacier/s-k8-releases#41]
Demo video:
https://glasswallsolu-qbp1117.slack.com/archives/C01A7PUQ2KU/p1600939277008600

Repo:
https://github.com/k8-proxy/chrome-extension
PR: https://github.com/k8-proxy/chrome-extension/pull/12

**Comment by GINAGC** [comment]
Release notes:
https://github.com/k8-proxy/chrome-extension

**Comment by IslamHeggy** [comment]
After reviewing the repo, here are my comments.

* In all the cases we need to containerize the application before doing anything
 
We have three options regarding this repo deployment and this will vary according to the purpose of the deployment.

## First Option 
If we need to just deploy for testing purpose, then this can be achieved by auto deploying the containers to any cloud platform and test with your host
## Second Option
If we need to use it for marketing purposes we most probably will need to use the OVA approach
**NOTE** We can use the first option here too  

## Third Option 
Deploying for production purposes and this may need further communication about production architecture

Appreciate your feedback 
@NourEddineX @mahnouman

**Comment by GINAGC** [comment]
@IslamHeggy, @mahnouman the releases are for testing purposes and so each team can share and formally delivered what they have done so far. That is why each release should also have a demo and the release notes.

**Comment by IslamHeggy** [comment]
Created the first release https://github.com/k8-proxy/chrome-extension/releases.
Deployed the chrome extension to the AMI and OVA in https://github.com/k8-proxy/chrome-extension/pull/19

@GINAGC
