### ISSUE TITLE
Release 0.5 Dockerize two project build

### ISSUE THREAD

**Issue by susilparida** [k8-proxy-glacier/s-k8-releases#54]
Dockerise below two project build

#p1-p-k8-test-data - https://github.com/k8-proxy/k8-test-data/releases/tag/k-8-test-data-v0.3 
#p2-p-chrome-extension - https://github.com/k8-proxy/chrome-extension

For k8-test-data .env Please ask Samarth.

**Comment by IslamHeggy** [comment]
chrome extension is already dockerized https://github.com/k8-proxy/chrome-extension/releases/tag/v0.2
test data is already dockerized too https://github.com/k8-proxy/k8-test-data/blob/master/docker-compose.yaml

So this issue is not valid anymore
